livox_imu_test:
  ros__parameters:
    imu_topic: "livox/imu"
    bias_sample_count: 1000
    clip_enable: true
    clip_max_rad_per_s: 5.0
    lpf_enable: true
    lpf_alpha: 0.2
    dt_check_enable: true
    dt_min: 0.003
    dt_max: 0.006
    marker_frame: "livox_frame"
    marker_topic: "imu_arrow"
